# Generated by Django 6.0.6 on 2026-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaj',
            old_name='data_trimiterii',
            new_name='data_trimitere',
        ),
        migrations.AddField(
            model_name='task',
            name='data_finalizarii',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='data_inceperii',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_asteptare', 'În așteptare'), ('in_lucru', 'În lucru'), ('finalizat', 'Finalizat')], default='in_asteptare', max_length=20),
        ),
    ]
