# Generated by Django 6.0.6 on 2026-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_trimiterii_mesaj_data_trimitere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actiune',
            field=models.CharField(default='Actiune noua', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='locatie',
            field=models.CharField(default='Locatie noua', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='descriere',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='titlu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
