# Generated by Django 6.0.6 on 2026-06-18 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_actiune_task_locatie_alter_task_descriere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='atribuit_catre',
        ),
        migrations.AddField(
            model_name='task',
            name='atribuit_catre',
            field=models.ManyToManyField(related_name='taskuri_primite', to=settings.AUTH_USER_MODEL),
        ),
    ]
