# Generated by Django 6.0.6 on 2026-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_task_atribuit_catre_task_atribuit_catre'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observatii',
            field=models.TextField(blank=True, verbose_name='Observații suplimentare'),
        ),
    ]
