# Generated by Django 6.0.6 on 2026-06-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_observatii'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notificare_trimisa',
            field=models.BooleanField(default=False),
        ),
    ]
