# Generated by Django 6.0.6 on 2026-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_notificare_trimisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='raport_finalizare',
            field=models.TextField(blank=True, verbose_name='Raport Finalizare (Angajat)'),
        ),
    ]
