# Generated by Django 6.0.6 on 2026-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_raport_finalizare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prioritate',
            field=models.CharField(choices=[('scazuta', 'Scăzută'), ('normala', 'Normală'), ('ridicata', 'Ridicată'), ('critica', 'Critică')], default='normala', max_length=10),
        ),
    ]
