# Generated by Django 6.0.6 on 2026-06-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_prioritate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notificare_trimisa',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prioritate',
        ),
    ]
