# Generated by Django 6.0.6 on 2026-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_task_notificare_trimisa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='raport_finalizare',
        ),
        migrations.AddField(
            model_name='task',
            name='notificare_trimisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='prioritate',
            field=models.CharField(choices=[('scazuta', 'Scăzută'), ('normala', 'Normală'), ('urgenta', 'Urgentă')], default='normala', max_length=20),
        ),
    ]
