# Generated by Django 6.0.6 on 2026-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_raport_finalizare'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timp_lucrat_secunde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='ultima_reluare',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
