# Generated by Django 6.0.6 on 2026-06-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitudine_inceput',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitudine_inceput',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
