# Generated by Django 6.0.6 on 2026-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_task_latitudine_inceput_task_longitudine_inceput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('manager', 'Manager'), ('gestionar', 'Gestionar'), ('sofer', 'Sofer'), ('tehnician', 'Tehnician'), ('inginer', 'Inginer')], default='angajat', max_length=20),
        ),
    ]
