# Generated by Django 6.0.6 on 2026-06-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timp_efectiv_secunde',
            field=models.IntegerField(default=0),
        ),
    ]
