# Generated by Django 6.0.6 on 2026-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_task_timp_efectiv_secunde'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suma_pauze_secunde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='ultima_incepere_pauza',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
