# Generated by Django 6.0.6 on 2026-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_suma_pauze_secunde_task_ultima_incepere_pauza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timp_efectiv_secunde',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ultima_reluare',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_asteptare', 'În așteptare'), ('in_lucru', 'În lucru'), ('in_pauza', 'În pauză'), ('finalizat', 'Finalizat')], default='in_asteptare', max_length=20),
        ),
    ]
