# Generated by Django 6.0.6 on 2026-07-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_task_timp_efectiv_secunde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supervizor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskuri_de_supervizat', to=settings.AUTH_USER_MODEL, verbose_name='Responsabil Locație / Supervizor'),
        ),
        migrations.CreateModel(
            name='RaportSupervizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_raportului', models.DateTimeField(auto_now_add=True, verbose_name='Data și Ora Controlului')),
                ('ce_s_a_facut', models.TextField(help_text='Descrie detaliat ce s-a montat, configurat sau reparat pe locație.', verbose_name='Ce a realizat angajatul / Lucrări efectuate')),
                ('ce_nu_s_a_facut', models.TextField(blank=True, help_text='Menționează ce a rămas neterminat, lipsă materiale sau greșeli.', null=True, verbose_name='Ce NU s-a realizat / Probleme întâmpinate')),
                ('stare_lucrare', models.CharField(choices=[('in_grafic', '🟢 În Grafic / Fără Probleme'), ('intarzieri', '🟡 Întârzieri / Probleme Minore'), ('critic', '🔴 Critic / Necesită Intervenție Urgentă')], default='in_grafic', max_length=30, verbose_name='Starea Lucrării')),
                ('angajat_evaluat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluari_primite', to=settings.AUTH_USER_MODEL, verbose_name='Angajat Verificat (Opțional)')),
                ('supervizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapoarte_create', to=settings.AUTH_USER_MODEL, verbose_name='Responsabil care raportează')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapoarte_control', to='core.task', verbose_name='Lucrare / Locație')),
            ],
            options={
                'verbose_name': 'Raport Supervizor / Intervenție',
                'verbose_name_plural': 'Rapoarte Supervizori / Intervenții',
                'ordering': ['-data_raportului'],
            },
        ),
    ]
