# Generated by Django 6.0.6 on 2026-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_task_supervizor_raportsupervizor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('manager', 'Manager'), ('supervizor', 'Supervizor / Control'), ('gestionar', 'Gestionar'), ('sofer', 'Sofer'), ('tehnician', 'Tehnician'), ('inginer', 'Inginer')], default='angajat', max_length=20),
        ),
    ]
