"""
import mimetypes
mimetypes.add_type("text/css", ".css", True)
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6zt(g)x3_m46oc7f5h3@cg_p%a-sr+h(1*=aez3@u005!mi-2!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# 1. Permitem accesul de pe orice IP/Domeniu
ALLOWED_HOSTS = ['cc210d3d8ceb.sn.mynetname.net', '127.0.0.1', 'localhost', '*']

# Adăugăm IP-ul tău public aici. Punem și varianta cu portul 8000 pentru siguranță.
CSRF_TRUSTED_ORIGINS = [
    'http://86.120.150.58',
    'http://86.120.150.58:8000', 
]
# --- SISTEM AUTOMAT DE DEBUGGING PENTRU PRODUCȚIE ---
import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detaliat': {
            'format': '{levelname} | {asctime} | Modul: {module} | Mesaj: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            # Fișierul va fi creat automat în același folder cu manage.py
            'filename': os.path.join(BASE_DIR, 'django_erori_sistem.log'),
            'formatter': 'detaliat',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notificari',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'core.User'
# Setare pentru testare: afiseaza continutul emailurilor direct in terminalul VS Code
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Setari pentru Login / Logout
LOGIN_REDIRECT_URL = 'dashboard' # Te trimite direct pe panoul principal dupa logare
LOGIN_URL = 'login' # Daca un vizitator acceseaza direct un link ascuns, il aduce aici
# --- SETĂRI PENTRU TRIMITERE EMAIL (Exemplu Gmail) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tehnic.ifis@gmail.com' # Email-ul tău
EMAIL_HOST_PASSWORD = 'apqnevmfeexdkkag' # NU PAROLA TA, ci cea de tip App Password!
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BFEX0J26VD1A9wjzrzuR4NTR1L7-8xLmeu7yKPE_qSygu1Mk6xWq5qHHew5rd0_qAOOZMxe4FGYqxyqHw-Zc7Gs",
    "VAPID_PRIVATE_KEY": "zV0IjdQ_rlSqBoy7MkmKLguNrwOsObQzfU9wguA9zCg",
    "VAPID_ADMIN_EMAIL": "dobroiufelix@gmail.com",


}
import os
# Aceasta este calea unde se vor aduna toate fișierele când rulezi collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Aceasta este calea pe care o vei folosi în Caddy pentru a servi fișierele
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
CSRF_TRUSTED_ORIGINS = [
    'https://cc210d3d8ceb.sn.mynetname.net',
    'https://*.trycloudflare.com', # Adaugă asta dacă folosești des link-uri temporare
]
